spring:
  datasource:
    url: jdbc:h2:mem:premiumhub;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret: dGhpcy1pcy1hLXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1wcmVtaXVtaHViLTI1Ng==

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

aes:
  secret: dGhpcy1pcy0xNi1ieXRlcw==
